"""empty message

Revision ID: 31ee1e130861
Revises: 
Create Date: 2018-02-26 16:49:53.778155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ee1e130861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_items',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tbl_type',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('terms', sa.String(length=500), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('enable', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('tbl_signature_sheet',
    sa.Column('id_signature', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Date(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.String(length=12), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('phone', sa.String(length=55), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('last', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_type'], ['tbl_type.id_type'], ),
    sa.PrimaryKeyConstraint('id_signature')
    )
    op.create_table('tbl_images',
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('id_signature', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('image_url', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_signature'], ['tbl_signature_sheet.id_signature'], ),
    sa.PrimaryKeyConstraint('id_image')
    )
    op.create_table('tbl_signature_x_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.String(length=20), nullable=False),
    sa.Column('ciid', sa.Integer(), nullable=True),
    sa.Column('id_signature', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id_signature'], ['tbl_signature_sheet.id_signature'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_signature_x_product')
    op.drop_table('tbl_images')
    op.drop_table('tbl_signature_sheet')
    op.drop_table('tbl_type')
    op.drop_table('tbl_items')
    # ### end Alembic commands ###
