"""empty message

Revision ID: e3345859e1c7
Revises: 
Create Date: 2018-07-04 14:06:32.813988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3345859e1c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_items',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tbl_license',
    sa.Column('id_license', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_product', sa.String(length=150), nullable=False),
    sa.Column('licences', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('adquisition_date', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('version_product', sa.String(length=8), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('accountable', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('enable', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id_license')
    )
    op.create_table('tbl_privileges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('privilege_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_roles',
    sa.Column('id_role', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('tbl_type',
    sa.Column('id_type', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('terms', sa.String(length=500), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('enable', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('tbl_privileges_x_roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_privilege', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_privilege'], ['tbl_privileges.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['tbl_roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_role', 'id_privilege')
    )
    op.create_table('tbl_signature_sheet',
    sa.Column('id_signature', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated', sa.Date(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.String(length=12), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('phone', sa.String(length=55), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('last', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_type'], ['tbl_type.id_type'], ),
    sa.PrimaryKeyConstraint('id_signature')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('modified_by', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['tbl_roles.id_role'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_workstatios_license',
    sa.Column('id_relationship', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_license', sa.Integer(), nullable=False),
    sa.Column('name_computer', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('enable', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['id_license'], ['tbl_license.id_license'], ),
    sa.PrimaryKeyConstraint('id_relationship')
    )
    op.create_table('tbl_images',
    sa.Column('id_image', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_signature', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('image_url', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_signature'], ['tbl_signature_sheet.id_signature'], ),
    sa.PrimaryKeyConstraint('id_image')
    )
    op.create_table('tbl_signature_x_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.String(length=25), nullable=False),
    sa.Column('ciid', sa.Integer(), nullable=True),
    sa.Column('id_signature', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=65), nullable=False),
    sa.Column('serial_number', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['id_signature'], ['tbl_signature_sheet.id_signature'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_signature_x_product')
    op.drop_table('tbl_images')
    op.drop_table('tbl_workstatios_license')
    op.drop_table('tbl_users')
    op.drop_table('tbl_signature_sheet')
    op.drop_table('tbl_privileges_x_roles')
    op.drop_table('tbl_type')
    op.drop_table('tbl_roles')
    op.drop_table('tbl_privileges')
    op.drop_table('tbl_license')
    op.drop_table('tbl_items')
    # ### end Alembic commands ###
