"""empty message

Revision ID: f60ca8a70784
Revises: 
Create Date: 2018-01-18 11:44:51.546036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60ca8a70784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_type',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('terms', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=30), nullable=True),
    sa.Column('enable', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('tbl_signature_sheet',
    sa.Column('id_signature', sa.String(length=10), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=50), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_employee', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id_type'], ['tbl_type.id_type'], ),
    sa.PrimaryKeyConstraint('id_signature')
    )
    op.create_table('tbl_signature_x_product',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.String(length=15), nullable=False),
    sa.Column('id_signature', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_signature'], ['tbl_signature_sheet.id_signature'], ),
    sa.PrimaryKeyConstraint('id_product', 'id_signature'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_signature_x_product')
    op.drop_table('tbl_signature_sheet')
    op.drop_table('tbl_type')
    # ### end Alembic commands ###
